# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui
import scn


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(216, 276)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scray = QtWidgets.QPushButton(self.centralwidget)
        self.scray.setGeometry(QtCore.QRect(10, 0, 75, 23))
        self.scray.setObjectName("scray")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(120, 0, 75, 23))
        self.clear.setObjectName("clear")
        self.result = QtWidgets.QTextBrowser(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(10, 50, 181, 141))
        self.result.setObjectName("result")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 91, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 216, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        # 连接clicked事件
        self.scray.clicked.connect(self.scray_clicked)  # type: ignore
        self.clear.clicked.connect(self.result.clear)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "摇签小程序"))
        self.scray.setText(_translate("MainWindow", "起卦"))
        self.clear.setText(_translate("MainWindow", "清除"))
        self.label.setText(_translate("MainWindow", "摇签结果："))

    def scray_clicked(self):
        self.result.setText(scn.main())
